import "server-only";

export {
  ExecutionError,
  IllegalStateTransitionError,
  InvalidApprovalError,
  InvalidRunSnapshotError,
  PersistenceConfigurationError,
  PersistenceDataError,
  PersistenceUnavailableError,
  RepositoryNotFoundError,
  RepositoryRevisionConflictError,
  RunBlockedError,
  type ExecutionErrorCode,
} from "./errors";
export {
  cryptoIdGenerator,
  systemClock,
  type Clock,
  type IdGenerator,
} from "./infrastructure";
export { InMemoryExecutionRunRepository, type ExecutionRunRepository } from "./repository";
export { ExecutionRunService, type ExecutionRunServiceDeps } from "./run-service";
export {
  compareWalletRequestToRpcTransaction,
  createTransactionReceiptEvidence,
  comparisonResultSchema,
  onchainTransactionEvidenceV1Schema,
  rpcTransactionReceiptV1Schema,
  rpcTransactionV1Schema,
  transactionReceiptEvidenceV1Schema,
  type OnchainTransactionEvidenceV1,
  type TransactionReceiptEvidenceV1,
} from "./onchain-evidence";
export { applyRunEvent, persistedConfirmationPair } from "./transitions";
export {
  authorizeCorrelationRetryV4,
  authorizeProviderInvocationV4,
  beginBrickkenCorrelationV4,
  beginReprepareV4,
  exactCorrelationPairV4,
  markPreparedStaleV4,
  recordBrickkenCorrelatedV4,
  recordBrickkenStatusEvidenceV4,
  recordBroadcastHashV4,
  recordBroadcastUnknownV4,
  recordCorrelationUncertainV4,
  recordRepreparedV4,
  recordReprepareOutcomeV4,
  recordRpcTransactionV4,
  recordRpcReceiptEvidenceV4,
  recordTokenIdentityFromReadBackV4,
  recordWalletPromptAuthorizationV4,
  recordWalletRejectedV4,
  upgradePreparedRunToV4,
  type V4PreparationFoundationInput,
} from "./v4-transitions";
export {
  brickkenCorrelationV1Schema,
  brickkenStatusEvidenceV1Schema,
  nonceFreshnessEvidenceV1Schema,
  observedImmutableExecutionIdentityV1Schema,
  preparationAttemptV1Schema,
  rpcTransactionAuthorizationEvidenceV1Schema,
  tokenIdentityV1Schema,
  walletPromptAuthorizationRecordV1Schema,
} from "./v4-contracts";
export type {
  ApprovalRecord,
  ApprovalProofV1,
  ApprovalRecordV1,
  ApprovalRecordV2,
  AuditEvent,
  ExecutionRunEvent,
  ExecutionRun,
  ExecutionRunV1,
  ExecutionRunV2,
  ExecutionRunV3,
  ExecutionRunV4,
  IsoUtcTimestamp,
  OperationKind,
  OperationStage,
  OperationStageV4,
  PreparationAttemptV1,
  NonceFreshnessEvidenceV1,
  WalletPromptAuthorizationRecordV1,
  RpcTransactionAuthorizationEvidenceV1,
  BrickkenCorrelationAttemptV1,
  BrickkenCorrelationV1,
  BrickkenStatusEvidenceV1,
  TokenIdentityV1,
  RunPhase,
  RunStatus,
  TerminalOutcome,
  WriteOperation,
  WriteOperationV3,
  WriteOperationV4,
} from "./types";
